version: "2"

services:
  app:
    build: .docker/app/
    ports:
      - 80:80
    working_dir: /var/www
    volumes:
      - .:/var/www
      - .docker/app/default.conf:/etc/apache2/sites-available/000-default.conf
      - .docker/app/php.ini:/usr/local/etc/php/php.ini

  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application

  dbadmin:
    image: adminer
    ports:
      - 8080:8080
